# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    groups:
      gh-actions:
        patterns:
          - "*"
    reviewers:
      - "frgfm"
    assignees:
      - "frgfm"
  - package-ecosystem: "pip"
    directory: "api"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    reviewers:
      - "frgfm"
    assignees:
      - "frgfm"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "demo"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    reviewers:
      - "frgfm"
    assignees:
      - "frgfm"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    reviewers:
      - "frgfm"
    assignees:
      - "frgfm"
    open-pull-requests-limit: 10
