primary:
  - "type: feat"
  - "type: fix"
  - "type: improvement"
  - "type: misc"

secondary:
  - "func: build"
  - "ext: api"
  - "ext: ci"
  - "ext: demo"
  - "ext: docs"
  - "ext: references"
  - "ext: scripts"
  - "ext: tests"
  - "topic: docs"
  - "topic: style"
  - "module: models"
  - "module: nn"
  - "module: ops"
  - "module: optim"
  - "module: trainer"
  - "module: transforms"
  - "module: utils"
