changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - "type: breaking change"
    # NEW FEATURES
    - title: New Features 🚀
      labels:
        - "type: feat"
    # BUG FIXES
    - title: Bug Fixes 🐛
      labels:
        - "type: fix"
    # IMPROVEMENTS
    - title: Improvements
      labels:
        - "type: improvement"
    # MISC
    - title: Miscellaneous
      labels:
        - "type: misc"
