default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: .conda
      - id: debug-statements
        language_version: python3
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: ['--branch', 'main']
      - id: trailing-whitespace
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 'v3.6.0'
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.8.4'
    hooks:
      - id: ruff
        args: ["--fix", "--config", "pyproject.toml"]
      - id: ruff-format
        args: ["--config", "pyproject.toml"]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: '0.5.13'
    hooks:
      - id: uv-lock
        args: ["--locked", "--project", "api"]
