# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files
# https://github.com/conda/conda-build/pull/4480
# for conda-build > 3.21.9
# {% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
# {% set project = pyproject.get('project') %}
# {% set urls = pyproject.get('project', {}).get('urls') %}
package:
  name: pylocron
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
  fn: pylocron-{{ environ.get('BUILD_VERSION') }}.tar.gz
  url: ../dist/pylocron-{{ environ.get('BUILD_VERSION') }}.tar.gz

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python>=3.6, <4.0
    - setuptools

  run:
    - python>=3.6, <4.0
    - pytorch >=1.9.1, <2.0.0
    - torchvision >=0.10.1, <1.0.0
    - tqdm >=4.1.0
    - numpy >=1.17.2, <2.0.0
    - fastprogress >=1.0.0, <2.0.0
    - matplotlib >=3.0.0, <4.0.0
    - pillow >=8.4.0
    - huggingface_hub >=0.4.0

test:
  # Python imports
  imports:
    - holocron
    - holocron.models
    - holocron.nn
    - holocron.ops
    - holocron.optim
    - holocron.trainer
    - holocron.utils
  requires:
    - python

about:
  home: https://github.com/frgfm/Holocron
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Modules, operations and models for computer vision in PyTorch'
  # description: |
  #   {{ data['long_description'] | replace("\n", "\n    ") | replace("#", '\#')}}
  doc_url: https://frgfm.github.io/Holocron/
  dev_url: https://github.com/frgfm/Holocron
