# Project information
site_name: Holocron
site_url: https://frgfm.github.io/holocron
site_description: PyTorch implementations of recent Computer Vision tricks
site_author: François-Guillaume Fernandez
copyright: Copyright &copy; 2019-2025, François-Guillaume Fernandez

# Repository
repo_name: frgfm/holocron
repo_url: https://github.com/frgfm/holocron
edit_uri: blob/main/docs
remote_branch: gh-pages

# Configuration
theme:
  name: material
  locale: en
  highlightjs: true
  favicon: img/favicon.ico
  language: en
  logo: img/logo.png
  icon:
    repo: fontawesome/brands/github-alt
  palette:
  - media: (prefers-color-scheme)
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: black
    accent: cyan
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: white
    accent: cyan
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  features:
  - content.code.annotate
  - content.code.copy
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

# Plugins
plugins:
  search:
  autorefs:
  mkdocstrings:
    handlers:
      python:
        paths: [..]
        inventories:
        - https://docs.python.org/3/objects.inv
        - https://docs.pytorch.org/docs/stable/objects.inv
        - https://docs.pytorch.org/vision/stable/objects.inv
        - https://matplotlib.org/stable/objects.inv
        - https://pillow.readthedocs.io/en/stable/objects.inv
        options:
          allow_inspection: true
          extensions:
          - griffe_typingdoc
          find_stubs_package: true
          force_inspection: false
          show_bases: true
          parameter_headings: false
          show_root_heading: true
          show_root_full_path: false
          show_object_full_path: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          inherited_members: true
          members_order: source
          filters:
          - '!^_'
          show_submodules: false
          summary:
            attributes: false
          docstring_style: google
          docstring_section_style: spacy
          merge_init_into_class: true
          show_if_no_docstring: false
          annotations_path: brief
          show_signature_annotations: true
          separate_signature: true
          signature_crossrefs: true
          unwrap_annotated: true

# Extensions
markdown_extensions:
  toc:
    permalink: true
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
  pymdownx.inlinehilite:
  pymdownx.snippets:
  pymdownx.superfences:
  pymdownx.blocks.admonition:
    types:
    - note
    - attention
    - caution
    - danger
    - error
    - tip
    - hint
    - warning
    - info
    - check
  pymdownx.arithmatex:
    generic: true
extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
extra:
  analytics:
    provider: google
    property: G-NYXYENL0V8
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/frgfm/holocron
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/pylocron/
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/frg_fm
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/fgfm
  - icon: fontawesome/solid/globe
    link: https://fgfm.dev
nav:
  - Home: index.md
  - Getting started:
    - getting-started/installation.md
    - getting-started/notebooks.md
  - Package Reference:
    - Models:
      - reference/models/models.md
      - Classification:
        - reference/models/classification/resnet.md
        - reference/models/classification/resnext.md
        - reference/models/classification/res2net.md
        - reference/models/classification/tridentnet.md
        - reference/models/classification/convnext.md
        - reference/models/classification/pyconv_resnet.md
        - reference/models/classification/rexnet.md
        - reference/models/classification/sknet.md
        - reference/models/classification/darknet.md
        - reference/models/classification/darknetv2.md
        - reference/models/classification/darknetv3.md
        - reference/models/classification/darknetv4.md
        - reference/models/classification/repvgg.md
        - reference/models/classification/mobileone.md
    - Layers: reference/nn.md
    - Operators: reference/ops.md
    - Optimizers: reference/optim.md
    - Trainer: reference/trainer.md
    - Transforms: reference/transforms.md
    - Utils:
      - reference/utils.md
      - Data: reference/utils.data.md
  - Notes:
    - notes/changelog.md
