[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "holocron-api"
version = "0.2.2.dev0"
description = "Backend template for your Vision API with Holocron"
authors = ["François-Guillaume Fernandez <fg-feedback@protonmail.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/frgfm/Holocron"
keywords = ["backend", "api", "computer vision"]

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = ">=0.11.1"
fastapi = ">=0.100.0,<1.0.0"
python-multipart = "==0.0.5"
Pillow = ">=8.4.0,!=9.2.0"
onnxruntime = "^1.10.0"
huggingface-hub = ">=0.4.0,<1.0.0"
numpy = "^1.19.5"

[tool.poetry.dev-dependencies]
pytest = ">=7.2.0,<8.0.0"
pytest-asyncio = ">=0.14.0,<1.0.0"
httpx = ">=0.23.0"
requests = "^2.31.0"
