name: builds

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.8, 3.9, '3.10', 3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Cache python modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ matrix.python }}-${{ hashFiles('pyproject.toml') }}-build
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e . --upgrade
      - name: Import package
        run: python -c "import holocron; print(holocron.__version__)"

  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: x64
      - name: Cache python modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ matrix.python }}-${{ hashFiles('pyproject.toml') }}-build
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine --upgrade
      - run: |
          python setup.py sdist bdist_wheel
          twine check dist/*

  conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.9"
      - name: Install dependencies
        shell: bash -el {0}
        run: conda install -y conda-build conda-verify
      - name: Build conda
        shell: bash -el {0}
        run: |
          python setup.py sdist
          mkdir conda-dist
          conda env list
          conda-build .conda/ -c pytorch -c fastai -c conda-forge --output-folder conda-dist
          ls -l conda-dist/noarch/*tar.bz2

  api:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.9]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.6.1
      - name: Lock the requirements
        run: |
          cd api
          poetry lock
          poetry export -f requirements.txt --without-hashes --output requirements.txt
      - name: Build & run docker
        run: cd api && docker compose up -d --build
      - name: Docker sanity check
        run: sleep 15 && nc -vz localhost 8050
      - name: Ping server
        run: curl http://api.localhost:8050/docs
