name: docker

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  docker-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -t holocron:latest-py3.8.1-slim
      - name: Run docker container
        run: docker run holocron:latest-py3.8.1-slim python -c 'import holocron'

  pytest-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & run docker
        run: PORT=8002 docker-compose up -d --build
      - name: Install dependencies in docker
        run: |
          PORT=8002 docker-compose exec -T web python -m pip install --upgrade pip
          PORT=8002 docker-compose exec -T web pip install -r requirements-dev.txt
      - name: Run docker test
        run: PORT=8002 docker-compose exec -T web pytest .
