name: docker

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -t holocron:python3.8.1-slim
      - name: Run docker container
        run: docker run holocron:python3.8.1-slim python -c 'import holocron'

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & run docker
        run: docker-compose up -d --build
      - name: Docker sanity check
        run: sleep 10 && nc -vz localhost 8080
      - name: Ping server
        run: curl http://localhost:8080/docs
      - name: Run docker test
        run: |
          docker-compose exec -T holocron pip install -r requirements-dev.txt
          docker-compose exec -T holocron pytest tests/
