name: docker

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -t holocron:python3.8-slim
      - name: Run docker container
        run: docker run holocron:python3.8-slim python -c 'import holocron'

  api:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3.0
      - name: Lock the requirements
        run: |
          cd api
          poetry lock
          poetry export -f requirements.txt --without-hashes --output requirements.txt
          poetry export -f requirements.txt --without-hashes --dev --output requirements-dev.txt
      - name: Build & run docker
        run: cd api && docker-compose up -d --build
      - name: Docker sanity check
        run: sleep 15 && nc -vz localhost 8080
      - name: Ping server
        run: curl http://localhost:8080/docs
      - name: Run docker test
        run: |
          docker cp api/requirements-dev.txt api_backend_1:/app/requirements-dev.txt
          docker-compose -f api/docker-compose.yml exec -T backend pip install -r requirements-dev.txt
          docker cp api/tests api_backend_1:/app/tests
          docker-compose -f api/docker-compose.yml exec -T backend pytest tests/
