name: push
on:
  push:
    branches: main

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"
      - name: Resolve dependencies
        run: cd api && poetry export -f requirements.txt --without-hashes --output api/requirements.txt
      - name: Build docker
        run: cd api && docker build src/. -t frgfm/holocron:latest
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: frgfm
          password: ${{ secrets.DOCKERHUB_PW }}
      - name: Push to hub
        run: docker push frgfm/holocron:latest
