name: push
on:
  push:
    branches: main

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"
      - name: Resolve dependencies
        run: cd api && poetry export -f requirements.txt --without-hashes --output requirements.txt
      - name: Build docker
        run: cd api && docker build api/. -t frgfm/holocron:latest
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: frgfm
          password: ${{ secrets.DOCKERHUB_PW }}
      - name: Push to hub
        run: docker push frgfm/holocron:latest
