name: tmp-comment

on:
  pull_request:
    branches: master

jobs:
  is-properly-labeled:
    runs-on: ubuntu-latest

    steps:
      - name: Ping merger responsible for labeling if necessary
        run: echo "${{ github.event.pull_request.user.login }}, ${{ github.event.pull_request.merged_by.login }}, ${{ github.event.pull_request.labels }}"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
      - name: Process commit and find merger responsible for labeling
        id: commit
        run: echo "::set-output name=merger::$(python .github/verify_labels.py ${{ github.event.pull_request.number }})"
      - name: 'Comment PR'
        uses: actions/github-script@0.3.0
        if: ${{ steps.commit.outputs.merger != '' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'Hey ${{ steps.commit.outputs.merger }} 👋\nYou merged this PR, but no labels were added. The list of valid labels is available at https://github.com/frgfm/Holocron/blob/master/.github/process_commit.py' });