name: tmp-comment

on:
  pull_request:
    branches: master

jobs:
  is-properly-labeled:
    runs-on: ubuntu-latest

    steps:
      - name: Ping merger responsible for labeling if necessary
        run: echo "${{ github.event.pull_request.user.login }} ${{ github.event.pull_request.merged_by.login }}, ${{ github.event.pull_request.labels }}"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
      - name: Check labels validity
        id: labels
        run: echo "::set-output name=valid::$(python .github/verify_labels.py ${{ github.event.pull_request.labels }})"
      - name: Ping merger responsible for labeling if necessary
        run: echo "Is valid ${{ steps.labels.outputs.valid }}"
